[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "core"
version = "0.1.0"
dependencies = [
  "fsspec>=2026.1.0",
  "python-dotenv>=1.0",
  "s3fs>=2026.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/core"]
